# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HMSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMSApp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='HostelAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designtion', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostelBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=50)),
                ('occupancy', models.IntegerField()),
                ('total_rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomAllotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('allotted_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotted', to='HMSApp.HostelBlock')),
                ('preferred_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='HMSApp.HostelBlock')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMSApp.Student')),
            ],
        ),
    ]
