# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSApp', '0004_auto_20180301_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='subject',
            field=models.CharField(default='electrical', max_length=255),
            preserve_default=False,
        ),
    ]
