# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMSApp', '0007_roomallotment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallotment',
            name='allotted_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allotted', to='HMSApp.HostelBlock'),
        ),
    ]
