# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSApp', '0008_auto_20180302_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelblock',
            name='allotted_rooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
