# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSApp', '0010_noticeboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
