# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSApp', '0012_roomallotment_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallotment',
            name='room_no',
            field=models.IntegerField(null=True),
        ),
    ]
